import { CubeColor, Face, CubeState, CubeSize, Language } from './types';

export const FACE_ORDER = [Face.F, Face.R, Face.B, Face.L, Face.U, Face.D];

export const FACE_NAMES: Record<Face, string> = {
  [Face.F]: 'Front (Green)',
  [Face.R]: 'Right (Red)',
  [Face.B]: 'Back (Blue)',
  [Face.L]: 'Left (Orange)',
  [Face.U]: 'Up (White)',
  [Face.D]: 'Down (Yellow)',
};

// Colors remain constant
export const FACE_CENTER_COLORS: Record<Face, CubeColor> = {
  [Face.F]: 'green',
  [Face.R]: 'red',
  [Face.B]: 'blue',
  [Face.L]: 'orange',
  [Face.U]: 'white',
  [Face.D]: 'yellow',
};

export const COLOR_HEX: Record<CubeColor, string> = {
  white: '#FFFFFF',
  yellow: '#FFD500',
  green: '#009E60',
  blue: '#0051BA',
  red: '#C41E3A',
  orange: '#FF5800',
  gray: '#334155',
};

// Helper to generate initial state for any size
export const getInitialCubeState = (size: CubeSize): CubeState => {
  const count = size * size;
  return {
    [Face.U]: Array(count).fill('white'),
    [Face.D]: Array(count).fill('yellow'),
    [Face.F]: Array(count).fill('green'),
    [Face.B]: Array(count).fill('blue'),
    [Face.L]: Array(count).fill('orange'),
    [Face.R]: Array(count).fill('red'),
  };
};

export const LEARN_TOPICS = [
  { id: '1', title: 'Basic Notation', description: 'Learn the language of cubes (R, U, F)', level: 'Beginner', duration: '5 min' },
  { id: '2', title: 'Layer by Layer', description: 'The fundamental method for 3x3', level: 'Beginner', duration: '20 min' },
  { id: '3', title: 'Finger Tricks', description: 'Move faster with proper finger placement', level: 'Intermediate', duration: '15 min' },
  { id: '4', title: '2-Look OLL', description: 'Orienting the last layer efficiently', level: 'Intermediate', duration: '30 min' },
  { id: '5', title: '4x4 Parity Errors', description: 'Fixing the impossible states', level: 'Advanced', duration: '10 min' },
];

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: 'CubeMaster Pro',
    subTitle: 'The Ultimate Intelligent Cube System',
    selectOrder: 'Select Cube Order',
    aiSolver: 'AI Solver',
    aiSolverDesc: 'Scan & Solve your cube',
    freePlay: 'Free Play',
    freePlayDesc: 'Virtual Cube',
    learn: 'Learn',
    learnDesc: 'Tutorials',
    scan: 'Scan',
    verify: 'Verify',
    solve: 'Solve Cube',
    calculating: 'Calculating Solution...',
    solved: 'Solved!',
    backHome: 'Back to Home',
    step: 'Step',
    nextMove: 'Next Move',
    rescan: 'Rescan',
    confirm: 'Confirm Face',
    retake: 'Retake',
    gestureControl: 'Gesture Control',
    touchControl: 'Touch Control',
    gestureTip: 'Wave hand: Up/Down/Left/Right',
    touchTip: 'Tap buttons to rotate',
    reset: 'Reset',
    mode: 'Mode',
  },
  zh: {
    appTitle: '魔方大师 Pro',
    subTitle: '终极智能魔方系统',
    selectOrder: '选择魔方阶数',
    aiSolver: 'AI 求解器',
    aiSolverDesc: '扫描并还原您的魔方',
    freePlay: '自由模式',
    freePlayDesc: '虚拟魔方',
    learn: '学习中心',
    learnDesc: '教程与技巧',
    scan: '扫描',
    verify: '验证',
    solve: '开始还原',
    calculating: '正在计算解法...',
    solved: '已还原！',
    backHome: '返回首页',
    step: '步骤',
    nextMove: '下一步',
    rescan: '重新扫描',
    confirm: '确认',
    retake: '重拍',
    gestureControl: '手势控制',
    touchControl: '触屏控制',
    gestureTip: '挥手方向：上/下/左/右',
    touchTip: '点击按钮旋转',
    reset: '重置',
    mode: '模式',
  },
  es: {
    appTitle: 'CubeMaster Pro',
    subTitle: 'Sistema Inteligente de Cubos',
    selectOrder: 'Seleccionar Orden',
    aiSolver: 'Solucionador IA',
    aiSolverDesc: 'Escanea y resuelve',
    freePlay: 'Juego Libre',
    freePlayDesc: 'Cubo Virtual',
    learn: 'Aprender',
    learnDesc: 'Tutoriales',
    scan: 'Escanear',
    verify: 'Verificar',
    solve: 'Resolver',
    calculating: 'Calculando...',
    solved: '¡Resuelto!',
    backHome: 'Volver al Inicio',
    step: 'Paso',
    nextMove: 'Siguiente',
    rescan: 'Re-escanear',
    confirm: 'Confirmar',
    retake: 'Retomar',
    gestureControl: 'Control Gestual',
    touchControl: 'Control Táctil',
    gestureTip: 'Mover mano: Arriba/Abajo...',
    touchTip: 'Tocar botones para rotar',
    reset: 'Reiniciar',
    mode: 'Modo',
  },
  fr: {
    appTitle: 'CubeMaster Pro',
    subTitle: 'Système Intelligent de Cube',
    selectOrder: 'Choisir la Taille',
    aiSolver: 'Résolveur IA',
    aiSolverDesc: 'Scanner et résoudre',
    freePlay: 'Jeu Libre',
    freePlayDesc: 'Cube Virtuel',
    learn: 'Apprendre',
    learnDesc: 'Tutoriels',
    scan: 'Scanner',
    verify: 'Vérifier',
    solve: 'Résoudre',
    calculating: 'Calcul en cours...',
    solved: 'Résolu !',
    backHome: 'Retour Accueil',
    step: 'Étape',
    nextMove: 'Suivant',
    rescan: 'Rescanner',
    confirm: 'Confirmer',
    retake: 'Reprendre',
    gestureControl: 'Contrôle Gestuel',
    touchControl: 'Contrôle Tactile',
    gestureTip: 'Agiter la main: Haut/Bas...',
    touchTip: 'Appuyez pour tourner',
    reset: 'Réinitialiser',
    mode: 'Mode',
  },
  ru: {
    appTitle: 'CubeMaster Pro',
    subTitle: 'Умная система кубика',
    selectOrder: 'Выберите размер',
    aiSolver: 'ИИ Решатель',
    aiSolverDesc: 'Сканируй и реши',
    freePlay: 'Свободная игра',
    freePlayDesc: 'Виртуальный куб',
    learn: 'Обучение',
    learnDesc: 'Уроки',
    scan: 'Сканировать',
    verify: 'Проверка',
    solve: 'Решить',
    calculating: 'Вычисление...',
    solved: 'Решено!',
    backHome: 'На главную',
    step: 'Шаг',
    nextMove: 'Далее',
    rescan: 'Переснять',
    confirm: 'Подтвердить',
    retake: 'Переснять',
    gestureControl: 'Жесты',
    touchControl: 'Сенсор',
    gestureTip: 'Взмах рукой: Вверх/Вниз...',
    touchTip: 'Нажмите для вращения',
    reset: 'Сброс',
    mode: 'Режим',
  },
  ar: {
    appTitle: 'CubeMaster Pro',
    subTitle: 'نظام المكعب الذكي',
    selectOrder: 'اختر حجم المكعب',
    aiSolver: 'حلال الذكاء الاصطناعي',
    aiSolverDesc: 'مسح وحل المكعب',
    freePlay: 'لعب حر',
    freePlayDesc: 'مكعب افتراضي',
    learn: 'تعلم',
    learnDesc: 'دروس',
    scan: 'مسح',
    verify: 'تحقق',
    solve: 'حل المكعب',
    calculating: 'جاري الحساب...',
    solved: 'تم الحل!',
    backHome: 'عودة للرئيسية',
    step: 'خطوة',
    nextMove: 'التالي',
    rescan: 'إعادة المسح',
    confirm: 'تأكيد',
    retake: 'إعادة',
    gestureControl: 'التحكم بالإيماءات',
    touchControl: 'التحكم باللمس',
    gestureTip: 'حرك يدك: فوق/تحت/يسار/يمين',
    touchTip: 'اضغط للتدوير',
    reset: 'إعادة تعيين',
    mode: 'الوضع',
  },
};